sudo: required
services:
  - docker

before_install:
  - docker build -t canbo123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run canbo123/react-test npm test -- --coverage

after_success:
  - docker build -t canbo123/multi-client ./client
  - docker build -t canbo123/multi-nginx ./nginx
  - docker build -t canbo123/multi-server ./server
  - docker build -t canbo123/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push canbo123/multi-client
  - docker push canbo123/multi-nginx
  - docker push canbo123/multi-server
  - docker push canbo123/multi-worker
